### ISSUE TITLE
Resolve TravisCI test error

### ISSUE THREAD

**Issue by greybutton** [applaura/web#5]
### What's the current situation?
Tests fails on travis-ci but locally it pass. It seems that travis-ci run tests parallel because of it data mix between tests in database. Locally tests run consistently and data does not mix.
[https://travis-ci.org/greybutton/web/builds/264572877](https://travis-ci.org/greybutton/web/builds/264572877)

### What do you recommend?
Determine why the test suite is failing and recommend a resolution.

**Comment by ufocoder** [comment]
You should run each test with it's initial state. Result of test shouldn't influence on the next one. Other words I suppose that It'll be better if you clear database before each test running and then load one and the same fixtures into database for each API test

**Comment by greybutton** [comment]
I guess, I clear database before each test. For example, https://github.com/applaura/web/blob/master/server/__test__/api/v1/areas/post.spec.js lines 13-17
```
beforeEach((done) => {
  User.remove({}).then(() => {
    done();
  });
});
```
Am I do it wrong?

**Comment by ufocoder** [comment]
According the [documentation](https://facebook.github.io/jest/blog/2016/09/01/jest-15.html#buffered-console-messages):
```
Jest parallelizes test runs across workers to maximize performance.
```

Also there' a proof that tests are running parallel. There're actual tests' cases:
* https://travis-ci.org/greybutton/web/builds/264572877#L530
* https://travis-ci.org/greybutton/web/builds/264572877#L532

But these strings come from two different tests:
https://github.com/applaura/web/blob/ba8ef5445ee4e31e33553578643a7da683cb848e/server/__test__/api/v1/areas/get.spec.js#L38
https://github.com/applaura/web/blob/ba8ef5445ee4e31e33553578643a7da683cb848e/server/__test__/api/v1/areas/post.spec.js#L137


====

So we need to run tests serially to make them consistent
